# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-06 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181206_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainshow',
            old_name='tarckid',
            new_name='trackid',
        ),
    ]
