# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-27 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
