# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-27 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elema', '0002_auto_20181127_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='score',
        ),
    ]
