# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-27 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elema', '0003_remove_student_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='English',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='math',
            field=models.IntegerField(default=0),
        ),
    ]
