# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-27 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elema', '0005_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cerate_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dateil',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='wwigth2',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
