# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-27 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elema', '0006_auto_20181127_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
