# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-28 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181128_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
